### ISSUE TITLE
WorldClass no lee bien las fechas con la IA

### ISSUE THREAD

**Issue by luisguareschi** [luisguareschi/Bot-Creacion-de-Pedidos#49]

**Comment by luisguareschi** [comment]
![Capture](https://user-images.githubusercontent.com/67588689/192763496-f0c5e35d-ed0b-4f08-ac9b-f5d9da1d911f.PNG)

**Comment by luisguareschi** [comment]
[Uploading openpowci2119.pdf…]()

**Comment by luisguareschi** [comment]
[openpowci2119 (1).pdf](https://github.com/luisguareschi/Bot-Creacion-de-Pedidos/files/9731502/openpowci2119.1.pdf)

**Comment by SergioAKKA** [comment]
Error arreglado
